---
#
# Ansible managed
#
repository:
  description: Install and configure podman on your system.
  homepage: https://robertdebock.nl/
  topics: podman, ansible, molecule, tox, playbook, hacktoberfest
